// Emilie LE ROUZIC
// Antoine PROVAIN
// Tanguy LE GOFF

import { useState, useEffect } from "react";
import axios from "axios";
import "./App.css";
import Banner from "./Banner";
import Footer from "./Footer";
function App() {
  const [imageUrl, setImageUrl] = useState(null); // Pour stocker l'URL de l'image
  const [isLoading, setIsLoading] = useState(false); // Etat du spinner
  const appName = import.meta.env.VITE_REACT_APP_OPENAI_API_KEY; // Clé OpenAI
  
  // Fonction send_request pour appeler l'API OpenAI
  const send_request = async (prompt) => {

    // Gestion prompt vide
    if (!prompt) {
      console.error("Prompt vide. Veuillez entrer un texte.");
      return;
    }

    // Lance le spinner
    setIsLoading(true)
    
    try {
      // Requette asynchrone vers OpenAI pour generer une image
      const response = await axios.post(
        "https://api.openai.com/v1/images/generations",
        {
          model: "dall-e-3",
          prompt: prompt, // Prompt entré dans le input
          n: 1,
          size: "1024x1024",
        },
        {
          headers: {
            Authorization: `Bearer ${appName}`,
            "Content-Type": "application/json",
          },
        }
      );
      setImageUrl(response.data.data[0].url); // Stocker l'URL de l'image
    } catch (error) {
      console.error("Error fetching image:", error);
    }finally{
      setIsLoading(false) // Arrete le spinner suite à la génération de l'image
    }
  };

  // Fonction déclenchée lors du clic sur le bouton
  // Lance send_request pour lancer la requete
  const generateImage = () => {
      const userInput = document.getElementById("message-input").value.trim();
      send_request(userInput); // Appeler la fonction d'API avec le texte entré
  };

  return (
  
    <div className="container">
      {/*  En tete  */}
      <Banner />
    

      {/* Corps de la page :
      Affiche "Pas d'image générée pour le moment" de base
      Affiche spinner si chargement de l'image
      Affiche image quand générée */}
      <div className="principale">
        {isLoading ? (
          <div>
            <img src="/spinner.gif" className="img"/>
          </div>
        ) : imageUrl ? (
          <a href={imageUrl} target="_blank" rel="noopener noreferrer">
            <img src={imageUrl} className="logo react" alt="Generated by DALL·E" />
          </a>
        ) : (
          <p>Pas d'image générée pour le moment</p>
        )}


        {/* input et bouton */}
        <div id="input-container">
          <input type="text" id="message-input" placeholder="Ecrivez votre prompt"></input>
          <button
            id="send-button"
            onClick={generateImage}
            disabled={isLoading} // Désactiver le bouton pendant le chargement
          >
            {isLoading ? "En cours d'exécution..." : "Envoyer"} {/* Texte selon état de chargement*/}
          </button>
        </div>
    

      </div>
      {/* Pied de page */}
      <Footer />
    </div>
  );
}

export default App;
